AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chatbase Proxy with Redis Cache and Airtable Logging

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Environment:
      Variables:
        CHATBASE_API_KEY: your-chatbase-api-key
        REDIS_URL: your-redis-connection-url
        AIRTABLE_API_KEY: your-airtable-api-key
        AIRTABLE_BASE_ID: your-airtable-base-id
        AIRTABLE_TABLE_NAME: your-airtable-table-name

Resources:
  ChatbaseProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.handler
      Events:
        ProxyAPI:
          Type: Api
          Properties:
            Path: /chatbase/proxy
            Method: POST
            RestApiId: !Ref ChatbaseApi

  ChatbaseApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ChatbaseProxyAPI
      StageName: prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Tenant-Id'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ChatbaseApi}.execute-api.${AWS::Region}.amazonaws.com/prod/chatbase/proxy"
